name: Test template

#runs:
#  using: 'composite'

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
jobs:
  easytest:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Inputs $INPUTS"
        env:
          INPUTS: ${{ inputs.project }}
      - name: git clone
        uses: actions/checkout@v2
      - name: npm install
        working-directory: ./${{ inputs.project }}
        run: npm i --force
      - name: Run Tests
        working-directory: ./${{ inputs.project }}
        run: npm run test:ci